<a href="https://colab.research.google.com/github/sushma535/font_detection_tesseract/blob/main/font_size_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!sudo apt install tesseract-ocr
!pip install pytesseract
!pip install Pillow
!pip install flask
!pip install img2html
!pip install Pylint
!pip install opencv-python


Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 37 not upgraded.
Need to get 4,795 kB of archives.
After this operation, 15.8 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 tesseract-ocr-eng all 4.00~git24-0e00fe6-1.2 [1,588 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 tesseract-ocr-osd all 4.00~git24-0e00fe6-1.2 [2,989 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/universe amd64 tesseract-ocr amd64 4.00~git2288-10f4998a-2 [218 kB]
Fetched 4,795 kB in 2s (2,196 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl

In [ ]:
import io
import pytesseract
from PIL import Image
import urllib

In [ ]:
import cv2
import numpy 
from os import listdir
from os.path import isfile, join
import os
import glob
from google.colab.patches import cv2_imshow
import cv2 as cv

mypath=glob.glob('/content/images/')

for img in mypath:
    print(mypath)
    n = cv.imread(img)
    cv_img.append(n)
print(images)
    # for x, image_src in enumerate(files):

    

    # for img in mypath:
    #     print(mypath)
    # n = cv.imread(img)
    # cv_img.append(n)
    # files = os.listdir(mypath)   

    # for idx, image_src in enumerate(files):
    # image = Image.open(f'{mypath}',"r") 
    # print(image)


['/content/images/']
[array([[[101, 189, 199],
        [101, 189, 199],
        [101, 189, 199],
        ...,
        [101, 189, 199],
        [101, 189, 199],
        [101, 189, 199]],

       [[101, 189, 199],
        [101, 189, 199],
        [101, 189, 199],
        ...,
        [101, 189, 199],
        [101, 189, 199],
        [101, 189, 199]],

       [[101, 189, 199],
        [101, 189, 199],
        [101, 189, 199],
        ...,
        [101, 189, 199],
        [101, 189, 199],
        [101, 189, 199]],

       ...,

       [[ 89, 134, 143],
        [ 90, 136, 144],
        [ 91, 137, 146],
        ...,
        [ 89, 136, 146],
        [ 89, 136, 145],
        [ 89, 136, 145]],

       [[ 90, 137, 146],
        [ 90, 138, 147],
        [ 92, 139, 148],
        ...,
        [ 89, 136, 145],
        [ 89, 136, 145],
        [ 89, 136, 145]],

       [[ 92, 141, 149],
        [ 93, 141, 150],
        [ 93, 141, 151],
        ...,
        [ 89, 136, 145],
        [ 89, 136, 145],
  

In [ ]:
import cv2
import pytesseract
from statistics import median
from PIL import Image
from bs4 import BeautifulSoup
from bs4 import BeautifulSoup as Soup
from bs4 import Tag
import re

images = [cv2.imread(file) for file in glob.glob("/content/images/*.png")]

for file in glob.glob("/content/images/*.png"):
  hocr = pytesseract.image_to_pdf_or_hocr(file, extension='hocr')

  data = hocr.decode("utf-8")

  soup = Soup(data, 'html.parser')
  font_spans = [ data for data in soup.select('span') if 'x_size' in str(data) ]
  output = []
  for i in font_spans:
    tup = ()
    fonts_size = re.search(r'(x_size)( .*?)[ 0-9.]+',str(i)).group()
    fonts_size = re.sub(r"x_size ", '' , fonts_size)

    tup = (str(i.text).strip(), fonts_size.strip())
    output.append(tup)
  print(file)     
  print(output)  
 

  

/content/images/animal1.png
[('', '17'), ('*', '17.652174'), ('50 Perfectly Timed Nature', '100'), ('Laugh Out Loud', '102'), ('"And then he said, ‘I\'m not texting other girls. |', '56'), ('Emma Baty, Adam Schubak Heath Owens Aug 28, 2021', '33'), ('', '1.5'), ('', '1'), ('', '60')]
/content/images/image2.png
[('Machine Hack', '34'), ('en ee on Cry (= toon)', '32.533333'), ('', '1'), ('', '8.5'), ('', '8.5'), ('', '1')]
/content/images/image.png
[('', '202.66666'), ('Simple. Flexible. Powerful.', '92'), ('', '60')]
/content/images/weather.png
[('€ C 0 A Notsecure | bom.gov.au/?ref=hdr', '21.25'), ('', '193.75'), ('Ber Ur Rel alas', '44.769234'), ('Bureau of Meteorology', '41'), ('', '0.5'), ('', '0.5'), ('', '189.33333'), ('', '1'), ('', '19'), ('', '19'), ('', '19'), ('rey', '26'), ('8 acon sai', '38.666664'), ('', '19'), ('', '19'), ('', '19'), ('', '19'), ('', '8.5'), ('', '8.5'), ('', '1'), ('', '0.5'), ('', '0.5')]
/content/images/animal.png
[('€ > GS QO @ pexels.com/search/anima

In [167]:
import cv2
import pytesseract
from statistics import median
path = '/content/images/'
# for file in glob.glob(path):
#    image_read = cv2.imread(file)
# print(image_read)

images = [cv2.imread(file) for file in glob.glob("/content/images/*.png")]

gray = cv2.cvtColor(images[0], cv2.COLOR_BGR2GRAY)
print(gray)
result = pytesseract.image_to_boxes(gray)
print(result)
lines = result.strip().split("\n")
font_size = []

for line in lines:
            chars = line.split(" ")
            try:
                font_size.append(float(chars[4]) - float(chars[2]))
            except Exception:
                font_size.append(12.0) 
font_size_img = int(median(font_size) * 1.7) 
 # Font-size value of the image
print(font_size_img)


[[182 182 182 ... 182 182 182]
 [182 182 182 ... 182 182 182]
 [182 182 182 ... 182 182 182]
 ...
 [132 133 134 ... 134 133 133]
 [134 135 136 ... 133 133 133]
 [138 138 139 ... 133 133 133]]
© 25 748 33 758 0
p 45 744 48 755 0
y 48 744 53 755 0
t 53 744 58 755 0
h 62 747 65 756 0
o 68 747 72 753 0
n 76 747 81 753 0
- 1366 0 1366 0 0
N 94 747 101 756 0
a 102 747 106 753 0
m 106 747 108 753 0
e 113 747 118 753 0
t 120 747 125 753 0
r 126 747 134 756 0
r 134 747 135 753 0
o 137 747 146 753 0
© 261 755 273 758 0
H 284 747 287 756 0
o 287 747 291 756 0
m 295 747 308 753 0
o 391 747 395 753 0
r 395 747 397 753 0
c 400 747 402 753 0
r 407 747 410 753 0
e 414 747 419 753 0
a 419 747 424 753 0
t 427 747 430 755 0
e 431 747 437 753 0
a 441 747 446 753 0
r 451 747 455 753 0
x 467 747 475 755 0
| 1366 0 1366 0 0
© 499 745 510 757 0
U 523 747 524 756 0
n 524 747 530 756 0
t 535 747 537 755 0
i 537 747 541 755 0
t 541 747 541 755 0
l 1366 0 1366 0 0
e 552 747 555 753 0
d 558 747 564 756 0
- 568 750